# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 0.64 -0.79  1.47 -0.85  2.11]
 [ 7.36  4.6   2.58 13.3  -0.17]
 [-1.41  0.58 -0.86 -1.16 -2.04]]
 
[[-1.29  1.85 -0.35  2.25]
 [ 1.38 -2.19 -0.24  0.02]
 [ 2.56 -1.41  1.72  2.27]
 [ 2.32 -2.46  0.49  1.68]
 [ 1.82 -3.75 -1.03 -0.65]
 [ 0.73 -1.13 -0.22  0.72]
 [ 0.07 -0.95 -1.08  1.51]]


# Using pytorch

In [7]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 0.3900, -2.1200, -0.9500,  0.0900,  0.2600],
        [-0.0300,  1.2200,  0.3900, -0.8900,  1.1400],
        [-0.4300,  3.3900,  0.1900, -2.3300, -0.8400]])
 
tensor([[-0.2700, -0.9600,  0.0400, -2.5100, -2.4200,  2.2300, -0.1700],
        [ 0.2400,  1.6000,  0.9300, -0.9300,  1.2400,  1.1500, -0.6900],
        [-1.1100,  0.2300, -1.5200,  3.9100,  1.6700, -2.3900,  0.2200]],
       dtype=torch.float64)
 
tensor([[-0.2700, -0.9600,  0.0400, -2.5100, -2.4200,  2.2300, -0.1700],
        [ 0.2400,  1.6000,  0.9300, -0.9300,  1.2400,  1.1500, -0.6900],
        [-1.1100,  0.2300, -1.5200,  3.9100,  1.6700, -2.3900,  0.2200]])


C:\Users\arumu\AppData\Local\Temp\ipykernel_25276\1942075091.py:10: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round( A@C1  ,2)), print(' ')
