# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Min/max and argmin/max
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [2]:
# import libraries
import numpy as np
import torch

# Using numpy

In [8]:
# create a vector
v = np.array([ 1,40,2,-3])

# find and report the maximum and minimum values
minval = np.min(v)
maxval = np.max(v)

print('Min,max: %g,%g' %(minval,maxval) )


# now for the argmin/max
minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min,max indices: %g,%g' %(minidx,maxidx) ), print(' ')

# confirm
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')

Min,max: -3,40
Min,max indices: 3,1
 
Min val is -3, max val is 40


In [12]:
# repeat with matrix
M = np.array([ [0,1,10], 
               [20,8,5] ])
print(M), print(' ')

# various minima in this matrix!
minvals1 = np.min(M)        # minimum from ENTIRE matrix
minvals2 = np.min(M,axis=0) # minimum of each column (across rows)
minvals3 = np.min(M,axis=1) # minimum of each row (across columns)

# print them out
print(f'np.min(M)={minvals1} minimum from ENTIRE matrix\n')
print(f'npmin(M,axis=0)={minvals2} minimum of each column (across rows)\n')
print(f'np.min(M,axis=1)={minvals3} minimum of each row (across columns)\n')
print(' ')

[[ 0  1 10]
 [20  8  5]]
 
np.min(M)=0 minimum from ENTIRE matrix

npmin(M,axis=0)=[0 1 5] minimum of each column (across rows)

np.min(M,axis=1)=[0 5] minimum of each row (across columns)

 


In [17]:
# various minima in this matrix!
minidx1 = np.argmin(M)        # minimum from ENTIRE matrix
minidx2 = np.argmin(M,axis=0) # minimum of each column (across rows)
minidx3 = np.argmin(M,axis=1) # minimum of each row (across columns)

# print them out
print(M), print(' ') # reminder
print(f'np.argmin(M)={minidx1} minimum from ENTIRE matrix\n')
print(f'np.argmin(M,axis=0)={minidx2} minimum of each column (across rows)\n')
print(f'np.argmin(M,axis=1)={minidx3} minimum of each row (across columns)\n')

[[ 0  1 10]
 [20  8  5]]
 
np.argmin(M)=0 minimum from ENTIRE matrix

np.argmin(M,axis=0)=[0 0 1] minimum of each column (across rows)

np.argmin(M,axis=1)=[0 2] minimum of each row (across columns)



In [20]:
# various maxima in this matrix!
maxvals1 = np.max(M)        # maximum from ENTIRE matrix
maxvals2 = np.max(M,axis=0) # maximum of each column (across rows)
maxvals3 = np.max(M,axis=1) # maximum of each row (across columns)

# print them out
print(M), print(' ') # reminder
print(f'np.max(M)={maxvals1} maximum from ENTIRE matrix\n')
print(f'np.max(M,axis=0)={maxvals2} maximum of each column (across rows)\n')
print(f'np.max(M,axis=1)={maxvals3} maximum of each row (across columns)\n')

[[ 0  1 10]
 [20  8  5]]
 
np.max(M)=20 maximum from ENTIRE matrix

np.max(M,axis=0)=[20  8 10] maximum of each column (across rows)

np.max(M,axis=1)=[10 20] maximum of each row (across columns)



In [23]:
# various maxima index in this matrix!
maxidx1 = np.argmax(M)        # maximum from ENTIRE matrix
maxidx2 = np.argmax(M,axis=0) # maximum of each column (across rows)
maxidx3 = np.argmax(M,axis=1) # maximum of each row (across columns)

# print them out
print(M), print(' ') # reminder
print(f'np.argmax(M)={maxidx1} maximum from ENTIRE matrix\n')
print(f'np.argmax(M,axis=0)={maxidx2} maximum of each column (across rows)\n')
print(f'np.argmax(M,axis=1)={maxidx3} maximum of each row (across columns)\n')

[[ 0  1 10]
 [20  8  5]]
 
np.argmax(M)=3 maximum from ENTIRE matrix

np.argmax(M,axis=0)=[1 1 0] maximum of each column (across rows)

np.argmax(M,axis=1)=[2 0] maximum of each row (across columns)



# Now using pytorch

In [24]:
# create a vector
v = torch.tensor([ 1,40,2,-3 ])

# find and report the maximum and minimum values
minval = torch.min(v)
maxval = torch.max(v)

print('Min,max: %g,%g' %(minval,maxval) )


# now for the argmin/max
minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('Min,max indices: %g,%g' %(minidx,maxidx) ), print(' ')

# confirm
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')

Min,max: -3,40
Min,max indices: 3,1
 
Min val is -3, max val is 40


In [34]:
# repeat with matrix
M = torch.tensor([ [0,1,10], 
                   [20,8,5] ])

# various minima in this matrix!
min1 = torch.min(M)        # minimum from ENTIRE matrix
min2 = torch.min(M,axis=0) # minimum of each column (across rows)
min3 = torch.min(M,axis=1) # minimum of each row (across columns)

# print them out
print(M), print(' ')
print(min1), print(' ')
print(min2), print(' ')
print(min1.values)
print(min1.indices), print(' ')
print(min2.values)
print(min2.indices), print(' ')
print(min3.values)
print(min3.indices), print(' ')

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
<built-in method values of Tensor object at 0x0000018C72311120>
<built-in method indices of Tensor object at 0x0000018C72311120>
 
tensor([0, 1, 5])
tensor([0, 0, 1])
 
tensor([0, 5])
tensor([0, 2])
 


(None, None)

In [31]:
min2.count

<function min.count(value, /)>