# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Identical randomness via seeding
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

In [4]:
# generate a few random numbers
np.random.randn(5)

array([-0.29353068,  1.9076292 , -0.38897589, -0.64536782, -1.24131553])

In [ ]:
# repeat after fixing the seed (old-but-still-widely-used method)
np.random.seed(17) # starts the initial seeding from which the randomness starts
# here the seed is set globally
print(np.random.randn(5))
print(np.random.randn(5))

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


# New seed mechanism in numpy

In [20]:
randseed1 = np.random.RandomState(17)
# here the seed is set to a specific object in this case which is randseed1
randseed2 = np.random.RandomState(20210530)

print( randseed1.randn(5) ) # same sequence
print( randseed2.randn(5) ) # different from above, but same each time
print( randseed1.randn(5) ) # same as two up
print( randseed2.randn(5) ) # same as two up
print( np.random.randn(5) ) # different every time

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
# [ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
# [ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[0.28458225 0.52253728 0.08355444 2.72079559 0.61100788]


In [35]:
import numpy as np

# Using np.random.seed for reproducibility
np.random.seed(17)
print('global random seeding')
print("First set of random numbers with global seed:", np.random.randn(5))
print("Second set of random numbers with global seed:", np.random.randn(5))

# Using RandomState to manage multiple independent streams
rng1 = np.random.RandomState(17)
rng2 = np.random.RandomState(18)
print('')
print('local randome seeding with rng1')
print("First set of random numbers with RandomState:", rng1.randn(5))
print("Second set of random numbers with RandomState:", rng1.randn(5))
print('')
print('local randome seeding with rng2')
print("First set of random numbers with RandomState:", rng2.randn(5))
print("Second set of random numbers with RandomState:", rng2.randn(5))

global random seeding
First set of random numbers with global seed: [ 0.27626589 -1.85462808  0.62390111]
Second set of random numbers with global seed: [1.14531129 1.03719047 1.88663893]

local randome seeding with rng1
First set of random numbers with RandomState: [ 0.27626589 -1.85462808  0.62390111]
Second set of random numbers with RandomState: [1.14531129 1.03719047 1.88663893]

local randome seeding with rng2
First set of random numbers with RandomState: [ 0.07942844  2.19020236 -0.13489215]
Second set of random numbers with RandomState: [0.16051798 0.44269784 0.62339144]


# Now in pytorch

In [9]:
torch.randn(5)

tensor([ 0.1534, -2.6631, -1.4311, -0.5483,  0.3232])

In [16]:
torch.manual_seed(17)
print( torch.randn(5) )

# torch's seed doesn't spread to numpy
print( np.random.randn(5) )

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 0.0991466   0.63792617  0.70311068 -0.91609315 -0.78601423]


In [44]:
import torch

# Using torch.manual_seed for reproducibility
torch.manual_seed(17)
print('global random seeding')
print("First set of random numbers with global seed:", torch.randn(5))
print("Second set of random numbers with global seed:", torch.randn(5))

# Using torch.Generator to manage multiple independent streams
trng1 = torch.Generator()
trng1.manual_seed(17)
trng2 = torch.Generator()
trng2.manual_seed(18)
print('')
print('local randome seeding with trng1')
print("First set of random numbers with Generator:", torch.randn(5, generator=trng1))
print("Second set of random numbers with Generator:", torch.randn(5, generator=trng1))
print('')
print('local randome seeding with trng2')
print("First set of random numbers with Generator:", torch.randn(5, generator=trng1))
print("Second set of random numbers with Generator:", torch.randn(5, generator=trng1))

global random seeding
First set of random numbers with global seed: tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
Second set of random numbers with global seed: tensor([-0.6124, -1.1835, -1.4831,  1.8004,  0.0096])

local randome seeding with trng1
First set of random numbers with Generator: tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
Second set of random numbers with Generator: tensor([-0.6124, -1.1835, -1.4831,  1.8004,  0.0096])

local randome seeding with trng2
First set of random numbers with Generator: tensor([ 0.1534, -2.6631, -1.4311, -0.5483,  0.3232])
Second set of random numbers with Generator: tensor([-0.4780,  1.5618, -0.1298, -0.1335,  1.2740])
