In [1]:
# Libraries are collection of functions and classes
import numpy as np

numbers = [1,2,3,4,5]

np.mean(numbers)

np.float64(3.0)

In [2]:
numbers

[1, 2, 3, 4, 5]

In [3]:
x = np.linspace(1,7,5)
x

array([1. , 2.5, 4. , 5.5, 7. ])

In [4]:
print(type(numbers))
print(type(x)) # a new data type called "numpy n nimensional array"

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
list(x)

[np.float64(1.0),
 np.float64(2.5),
 np.float64(4.0),
 np.float64(5.5),
 np.float64(7.0)]

In [6]:
number_np = np.array(numbers)
number_np

array([1, 2, 3, 4, 5])

In [7]:
list(number_np)

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [8]:
number_np.mean()

np.float64(3.0)

In [9]:
number_np.min()

np.int64(1)

In [10]:
number_np.max()

np.int64(5)

In [11]:
np.max(number_np)

np.int64(5)

In [12]:
np.max(numbers)

np.int64(5)

In [13]:
from numpy import mean as m
numbers = [1,2,3,4,5]
m(numbers)



np.float64(3.0)

In [14]:
# in-place operations
# out-of-place operations / not in-place operations

n = [4,3,5,2,6,1,7]
nn = np.array(n)

print(n)
n.sort() # In-Place Operations: These are operations that modify the original array directly without creating a new array for the result.
print(n)

print(nn)
nn.sort()
print(nn)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]
[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [15]:
n = [4,3,5,2,6,1,7]
nn = np.array(n)

print(nn)
nns = np.sort(nn) # Out-of-Place Operations: These operations create a new array as the result of the operation, 
#                                            leaving the original array unchanged.
print(nn) # out-of-place operation
print(nns)

[4 3 5 2 6 1 7]
[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [17]:

# Create an array
arr = np.array([1, 2, 3])
print("Original array:", arr)

# In-place operation (modifies the original array)
arr += 10
print("After in-place addition:", arr)

# Out-of-place operation (returns a new array)
new_arr = arr + 5
print("New array after out-of-place addition:", new_arr)
print("Original array remains unchanged:", arr)

Original array: [1 2 3]
After in-place addition: [11 12 13]
New array after out-of-place addition: [16 17 18]
Original array remains unchanged: [11 12 13]


In [20]:
np

<module 'numpy' from 'c:\\Users\\arumu\\github\\AI-ML_learning\\.venv\\lib\\site-packages\\numpy\\__init__.py'>

In [ ]:
type(np)


[1 2 3 4 5]
