In [ ]:
# Libraries are collection of functions and classes
import numpy as np

numbers = [1,2,3,4,5]

np.mean(numbers)

In [ ]:
numbers

In [ ]:
x = np.linspace(1,7,5)
x

In [ ]:
print(type(numbers))
print(type(x)) # a new data type called "numpy n nimensional array"

In [ ]:
list(x)

In [ ]:
number_np = np.array(numbers)
number_np

In [ ]:
list(number_np)

In [ ]:
number_np.mean()

In [ ]:
number_np.min()

In [ ]:
number_np.max()

In [ ]:
np.max(number_np)

In [ ]:
np.max(numbers)

In [14]:
from numpy import mean as m
numbers = [1,2,3,4,5]
m(numbers)



np.float64(3.0)

In [ ]:
# in-place operations
# out-of-place operations / not in-place operations

n = [4,3,5,2,6,1,7]
nn = np.array(n)

print(n)
n.sort() # In-Place Operations: These are operations that modify the original array directly without creating a new array for the result.
print(n)

print(nn)
nn.sort()
print(nn)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]
[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [24]:
n = [4,3,5,2,6,1,7]
nn = np.array(n)

print(nn)
nns = np.sort(nn) # Out-of-Place Operations: These operations create a new array as the result of the operation, 
#                                            leaving the original array unchanged.
print(nn) # out-of-place operation
print(nns)

[4 3 5 2 6 1 7]
[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [25]:

# Create an array
arr = np.array([1, 2, 3])
print("Original array:", arr)

# In-place operation (modifies the original array)
arr += 10
print("After in-place addition:", arr)

# Out-of-place operation (returns a new array)
new_arr = arr + 5
print("New array after out-of-place addition:", new_arr)
print("Original array remains unchanged:", arr)

Original array: [1 2 3]
After in-place addition: [11 12 13]
New array after out-of-place addition: [16 17 18]
Original array remains unchanged: [11 12 13]
