In [1]:
import numpy as np
import pandas as pd

# create a random data
print(np.random.randn()) # creates a random number of standard normal distribution with mean 0 and std 1
print(np.random.randn(5)) # creates a random vector of 5 numbers
print(np.random.randn(3, 4)) # creates a random matrix of 3 rows and 4 columns
print(np.random.randn(10)*5+20) # creates a random vector of 10 numbers with mean 20 and std 5

0.504106144883867
[-0.61537347 -0.86395902 -1.17186647 -0.08989277  0.22976203]
[[ 1.07279708  0.34347137  2.14010544  0.80438705]
 [ 1.80344383 -0.01855171  2.81351615  0.08146149]
 [ 0.26564265 -1.08664646 -0.00693479 -0.13348097]]
[22.71549129 18.61174423 19.65012376 18.72666315 26.238015   23.9797802
 23.85982363 24.41464691 17.06709248 20.77854742]


In [3]:
# createa random data
var1 = np.random.randn(10)*5+20
var2 = np.random.randn(10)>0 # creates a random vector of 100 boolean values

print(var1)
print(var2)

# variable labels
labels = ['Temp (C)', 'Ice Cream']

# create a dictionary from the random data on wether a person eats ice cream or not during every temperature
D = {labels[0]: var1, labels[1]: var2}
print(D)

# import the data into a pandas dataframe
df = pd.DataFrame(D)
print(df)
print(type(df))

[25.48107555 16.36690633 23.04919013 16.56413981 12.97540709 22.90751205
 20.4336432  19.33792806  4.31116991 15.51692628]
[ True  True  True  True False False  True False False  True]
{'Temp (C)': array([25.48107555, 16.36690633, 23.04919013, 16.56413981, 12.97540709,
       22.90751205, 20.4336432 , 19.33792806,  4.31116991, 15.51692628]), 'Ice Cream': array([ True,  True,  True,  True, False, False,  True, False, False,
        True])}
    Temp (C)  Ice Cream
0  25.481076       True
1  16.366906       True
2  23.049190       True
3  16.564140       True
4  12.975407      False
5  22.907512      False
6  20.433643       True
7  19.337928      False
8   4.311170      False
9  15.516926       True
<class 'pandas.core.frame.DataFrame'>


In [5]:
df.head() # shows the first 5 rows of the dataframe

Temp (C)  Ice Cream
0  25.481076       True
1  16.366906       True
2  23.049190       True
3  16.564140       True
4  12.975407      False

In [ ]:
df.count() # counts the number of non-null values in each row

Temp (C)     10
Ice Cream    10
dtype: int64

In [7]:
df.mean() # calculates the mean of each column in the dataframe

Temp (C)     17.69439
Ice Cream     0.60000
dtype: float64

In [8]:
df.std() # calculates the standard deviation of each column

Temp (C)     6.108720
Ice Cream    0.516398
dtype: float64

In [10]:
df.describe() # provides a summary of the dataframe

Temp (C)
count  10.000000
mean   17.694390
std     6.108720
min     4.311170
25%    15.729421
50%    17.951034
75%    22.289045
max    25.481076

In [15]:
# create a pandas data frame with:
# integers going from 0 to 10, thier square, and thier log
var1 = range (1,10)
var2 = [num**2 for num in var1] 
var3 = np.log(var1)

labels = ['Integer', 'Square', 'Log']

D = {labels[0]: var1, labels[1]: var2, labels[2]: var3}
df = pd.DataFrame(D)
print(df)


   Integer  Square       Log
0        1       1  0.000000
1        2       4  0.693147
2        3       9  1.098612
3        4      16  1.386294
4        5      25  1.609438
5        6      36  1.791759
6        7      49  1.945910
7        8      64  2.079442
8        9      81  2.197225


In [ ]:
num = np.array(range(1, 10))
df = pd.DataFrame({'Number': num, 'Square':num**2, 'Log':np.log(num)}) 
df

Number  Square       Log
0       1       1  0.000000
1       2       4  0.693147
2       3       9  1.098612
3       4      16  1.386294
4       5      25  1.609438
5       6      36  1.791759
6       7      49  1.945910
7       8      64  2.079442
8       9      81  2.197225