In [1]:
# classes and object oriented programming OOPs.
# class: blueprint for creating a set of attributes and methods.
# instance: an object created from a class. 

class model(object):
    # Constructor method
    def __init__(self,numlayers,numunits,name):
        self.layers     = numlayers # attribute
        self.units      = numunits
        self.name       = name
        self.weights    = 1
    def howManyUnits(self): # method
        totalUnits = self.layers * self.units
        print(f'There are {totalUnits} units in the model.')
    def trainTheModel(self,x):
        self.weights += x
        return self.weights
    def __str__(self):
        return f'This is a {self.name} architecture.'

In [2]:
m1 = model(2,5,'CNN') # m1 is an instance of class model

In [3]:
m1

In [4]:
m1.howManyUnits()

There are 10 units in the model.


In [5]:
m1 = model(12,5,'CNN')
m1.howManyUnits()

There are 60 units in the model.


In [6]:
m1.trainTheModel(2.5)

3.5

In [7]:
str(m1)

'This is a CNN architecture.'

In [ ]:
# Exercise: Create a new class
# 1) weights should be a random number matrix of size layers * units
# 2) change training method to multiply input X and add input Y

In [26]:
import numpy as np

class matrix_model:
    # Constructor method
    def __init__(self,numlayers,numunits,name):
        self.layers     = numlayers # attribute
        self.units      = numunits
        self.name       = name
        self.weights    = np.random.rand(numlayers, numunits)
    
    def displayWeight(self):
        print("The weights are: \n",self.weights)
    def training(self,X,Y):
        print("The weights before training are: \n",self.weights)
        self.weights = self.weights * X + Y
        print("The weights after training are: \n",self.weights)
    def __str__(self):
            return f'This is a {self.name} architecture.'



In [28]:
mm1 = matrix_model(2,1,'CNN')
mm1.displayWeight()
mm1.training(0.1,1)
str(mm1)


The weights are: 
 [[0.16689315]
 [0.97707348]]
The weights before training are: 
 [[0.16689315]
 [0.97707348]]
The weights after training are: 
 [[1.01668932]
 [1.09770735]]


'This is a CNN architecture.'