In [2]:
# Enumerate and Zip
import numpy as np

ns = np.linspace(-5,5,7)

for i in range(len(ns)):
    print('Index',i,' has a value of',ns[i])


Index 0  has a value of -5.0
Index 1  has a value of -3.333333333333333
Index 2  has a value of -1.6666666666666665
Index 3  has a value of 0.0
Index 4  has a value of 1.666666666666667
Index 5  has a value of 3.333333333333334
Index 6  has a value of 5.0


In [10]:
for i in range(len(ns)):
    n=ns[i]
    print('Index',i,' has a value of',n)

Index 0  has a value of -5.0
Index 1  has a value of -3.333333333333333
Index 2  has a value of -1.6666666666666665
Index 3  has a value of 0.0
Index 4  has a value of 1.666666666666667
Index 5  has a value of 3.333333333333334
Index 6  has a value of 5.0


In [ ]:
# simplifying the above with enumerate
for i,n in enumerate(ns): 
    print('Index', i, 'has a value of', n)
# i,n is a tuple unpacking, enumerate returns two values: index and element which is i and n respectively. where its equivalent to n=ns[i]


Index 0 has a value of -5.0
Index 1 has a value of -3.333333333333333
Index 2 has a value of -1.6666666666666665
Index 3 has a value of 0.0
Index 4 has a value of 1.666666666666667
Index 5 has a value of 3.333333333333334
Index 6 has a value of 5.0


In [ ]:
text = 'Hello my name is ARP'
vowels = np.zeros(len(text))
print("vowels before operation is \n",vowels)

# change in vowels where text has vowels
for i,n in enumerate(text):
    if n=='A' or n=='a' or n=='E' or n=='e' or n=='I' or n=='i' or n=='O' or n=='o' or n=='U' or n=='u':
        vowels[i] = 1

print("vowels after operation is \n",vowels)


vowels before operation is 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
vowels after operation is 
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0.]


In [15]:
for i,n in enumerate(text):
    if n in 'aeiou':
        vowels[i] = 1
# this will work for both lower and upper case
print("vowels after operation is \n",vowels)

vowels after operation is 
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0.]


In [17]:
listA = [3,4,5,6,3,-17]
listB = ['q','w','e','r','t','y']
for i in range(len(listA)):
    print(str(listA[i]) + ' '+ listB[i])

3 q
4 w
5 e
6 r
3 t
-17 y


In [ ]:
# usage of zip to simplify
for a,b in zip(listA, listB): # zip will pair the elements from both lists equivalent to a=listA[i] and b=listB[i]
    print(str( a )+ ' '+ b)

3 q
4 w
5 e
6 r
3 t
-17 y


In [ ]:
listA = [3,4,5,6]
listB = ['q','w','e','r','t','y']
for a,b in zip(listA, listB):
    print(str(a)+ ' '+ b)

# when zip is done for the shorter list it stops. In this case it will stop at index which is the shortest of two lists i.e 4 and then stop.

3 q
4 w
5 e
6 r


In [25]:
names = ['alpha', 'beta', 'gama']
values = [10,20,30]
# exercise: given the following list, create a dictionary using zip

name_value_dict = dict(zip( names, values)) # this will pair each element
print(name_value_dict)

# the hard way using loop
name_value_dict = {}
for i,j in zip(names,values):
    name_value_dict.update({i:j}) # this will update the dictionary with key value pair
print(name_value_dict)

{'alpha': 10, 'beta': 20, 'gama': 30}
{'alpha': 10, 'beta': 20, 'gama': 30}
