In [10]:
# initialising variables in python using assignment operator = and augmented operators +=, -=, *=, / = etc.

r = [0,0,0,0,0,0,0,0,0,0]
for i in range(10):
    r[i] = i**2
r

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [3]:
import numpy as np

r = np.zeros(10) # initialising array with zeros
r

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
r=np.full(10,7.8) # initialising array with a specific value
r

array([7.8, 7.8, 7.8, 7.8, 7.8, 7.8, 7.8, 7.8, 7.8, 7.8])

In [ ]:
N=10
r=np.zeros(N) # using variable to define size of the array
for i in range(N):
    r[i]=i**2
print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [6]:
# to delete a variable, use del statement
del r
r

NameError: name 'r' is not defined

In [ ]:
# to initialise a matrix for zero
r = np.zeros((4,5)) # creates a 3x4 array of zeros, where the input should be a tuple (rows, columns)
r

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
r=[]

for i in range(10):
    r.append(i**2)
r

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [13]:
r = np.array([])
for i in range(10):
    r = np.append(r,i**2)
r

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [ ]:
# compare three methods of creating an array
# N = 10000
# time test! use below
# import time
# time.perf_counter() gives the current time in seconds

In [50]:
N=100000
import numpy as np
import time

time_taken = [0]*3 # create a list with 3 elements all set to 0. This will store the time taken for each method.
print(time_taken)

start_time = time.perf_counter()
r=[]
for i in range(N):
    r.append(i**2)
end_time = time.perf_counter()
time_taken[0]=end_time - start_time
print("Time taken for list appending: ", time_taken[0]*1000, "milliseconds")
# print(r)

start_time = time.perf_counter()
r=np.array([])
for i in range(N):
    r = np.append(r,i**2)
end_time = time.perf_counter()
time_taken[1]=end_time - start_time
print("Time taken for numpy appending: ", time_taken[1]*1000, "milliseconds")
# print(r)

start_time = time.perf_counter()
r=np.zeros(N) # using variable to define size of the
for i in range(N):
    r[i] = i**2
end_time = time.perf_counter()
time_taken[2]=end_time - start_time
print("Time taken for numpy array indexing: ", time_taken[2]*1000, "milliseconds")
# print(r)

print("Time taken array is",time_taken)

if time_taken[0] < time_taken[1]:
    if time_taken[0] < time_taken[2]:
        print("List appending is fastest.")
    else:
        print("Numpy array indexing is fastest.")
else:
    if time_taken[1] < time_taken[2]:
        print("Numpy appending is fastest.")
    else:
        print("Numpy array indexing is fastest.")

[0, 0, 0]
Time taken for list appending:  21.611599950119853 milliseconds
Time taken for numpy appending:  917.762600001879 milliseconds
Time taken for numpy array indexing:  20.697400090284646 milliseconds
Time taken array is [0.021611599950119853, 0.917762600001879, 0.020697400090284646]
Numpy array indexing is fastest.
