In [4]:
# initialising variables in python using assignment operator = and augmented operators +=, -=, *=, / = etc.

r = [0,0,0,0,0,0,0,0,0,0]
for i in range(10):
    r[i] = i**2

In [ ]:
import numpy as np

r = np.zeros(10) # initialising array with zeros
r

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
r=np.full(10,7.8) # initialising array with a specific value
r

array([7.8, 7.8, 7.8, 7.8, 7.8, 7.8, 7.8, 7.8, 7.8, 7.8])

In [8]:
n=10
r=np.zeros(n) # using variable to define size of the array
for i in range(n):
    r[i]=i**2
print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [9]:
# to delete a variable, use del statement
del r
r

NameError: name 'r' is not defined

In [ ]:
# to initialise a matrix for zero
r = np.zeros((3,4)) # creates a 3x4 array of zeros
r

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])