In [8]:
import numpy as np

x=np.array([[1,2,3],
            [2,3,4],
            [3,4,5],
            [4,5,6]])
w = np.array([10,20,30])
print(x), print(" ")
print(w)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
 
[10 20 30]


In [9]:
y=np.copy(x)
for i in range(y.shape[0]):
    y[i, :] += w
y

array([[11, 22, 33],
       [12, 23, 34],
       [13, 24, 35],
       [14, 25, 36]])

In [10]:
y=np.zeros(x.shape)
for i in range(y.shape[0]):
    y[i,:] = x[i,:] + w
y

array([[11., 22., 33.],
       [12., 23., 34.],
       [13., 24., 35.],
       [14., 25., 36.]])

In [11]:
# broadcasting
z = x+w # this is not leagal in linear algebra but in python it works with broadcasting
print(z)

z = x*w
print(z)

z = x-w # not working as expected
print(z)

# this is a broadcasting row wise

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
[[ 10  40  90]
 [ 20  60 120]
 [ 30  80 150]
 [ 40 100 180]]
[[ -9 -18 -27]
 [ -8 -17 -26]
 [ -7 -16 -25]
 [ -6 -15 -24]]


In [12]:
# to broadcast column wise
v = np.array([[-1],[0],[1],[0]])
v

array([[-1],
       [ 0],
       [ 1],
       [ 0]])

In [13]:
v = np.array([-1,0,1,0],ndmin=2).T # ndmin specifies the dimension of array to be created and .T creates the transpose
v

array([[-1],
       [ 0],
       [ 1],
       [ 0]])

In [15]:
print(x,'\n+\n',v,'\n=\n',x+v)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]] 
+
 [[-1]
 [ 0]
 [ 1]
 [ 0]] 
=
 [[0 1 2]
 [2 3 4]
 [4 5 6]
 [4 5 6]]


In [16]:
print(x,"\n*\n",v,"\n=\n",x*v)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]] 
*
 [[-1]
 [ 0]
 [ 1]
 [ 0]] 
=
 [[-1 -2 -3]
 [ 0  0  0]
 [ 3  4  5]
 [ 0  0  0]]


In [ ]:
# Exercise :
# 1) create a vector of integers 0:8 (v)
# 2) reshape v into a 3x3 matrix (M) (np.reshape)
# 3) repeat M into a 9x3 (c) (np.tile)
# 4) broadcast-multiple c with v (B)

In [48]:
v = np.linspace(0,8,9)
print("v is ", v)

m = np.reshape(v,(3,3))
print("m is ",m)

c = np.tile(m,(1,3))
print("\nc 3x9 tiling\n",c)

c = np.tile(m,(3,1))
print("\nc 9x3 tiling\n",c)

b = c*np.reshape(v,(-1,1)) # also b = c*np.reshape(v,(len(v),1))
print("\nBroadcasting c*v\n",b)

v is  [0. 1. 2. 3. 4. 5. 6. 7. 8.]
m is  [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

c 3x9 tiling
 [[0. 1. 2. 0. 1. 2. 0. 1. 2.]
 [3. 4. 5. 3. 4. 5. 3. 4. 5.]
 [6. 7. 8. 6. 7. 8. 6. 7. 8.]]

c 9x3 tiling
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]
 [0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]
 [0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

Broadcasting c*v
 [[ 0.  0.  0.]
 [ 3.  4.  5.]
 [12. 14. 16.]
 [ 0.  3.  6.]
 [12. 16. 20.]
 [30. 35. 40.]
 [ 0.  6. 12.]
 [21. 28. 35.]
 [48. 56. 64.]]
